{
 "title": "Thesis Dashboard",
 "time": { "from": "2025-08-24T23:22:40.000Z", "to": "2025-08-24T23:28:00.000Z" },
 "panels": [
  {
   "title": "No validation end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{ssi_validation=\"false\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Key end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:key\", ssi_validation=\"true\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web no cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"False\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Ethr with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:ethr:sepolia\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}