{
 "title": "Thesis Dashboard",
 "time": { "from": "2025-08-24T23:22:40.000Z", "to": "2025-08-24T23:28:00.000Z" },
 "panels": [
  { "title": "Thesis project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No validation end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{ssi_validation=\"false\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Key end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:key\", ssi_validation=\"true\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage with no validation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[30s]) / scalar(machine_cpu_cores{instance=\"cadvisor:8080\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Key cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/\"}[30s]) / scalar(machine_cpu_cores{instance=\"cadvisor:8080\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No validation payload size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(data_synthesizer_finnhub_payload_size_bytes_bucket{}[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Key end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:key\", ssi_validation=\"true\"}[30s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_credential_verification_duration_seconds_bucket{ssi_validation=\"true\", did_provider=\"did:key\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(kafka_consumer_kafka_consumer_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Key end to end throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(kafka_consumer_message_end_to_end_latency_seconds_count{\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No validation throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_message_end_to_end_latency_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web no cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"False\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web with cache did resolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(credential_verifier_did_resolution_duration_seconds_bucket{}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage when verification enabled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_credential_verification_duration_seconds_bucket{cache_did=\"True\", did_provider=\"did:web\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation payload size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(data_synthesizer_finnhub_payload_size_bytes_bucket{}[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web with cache throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_message_end_to_end_latency_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web no cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:web\", cache_did=\"False\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Ethr with cache end to end throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(kafka_consumer_kafka_messages_consumed_total{\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web no cache end to end throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_message_end_to_end_latency_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Web no cache latency comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket[30s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_credential_verification_duration_seconds_bucket{cache_did=\"False\", did_provider=\"did:web\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Ethr resolution with cache latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(credential_verifier_did_resolution_duration_seconds_bucket{did_provider=\"did:ethr:sepolia\", cached=\"false\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Ethr with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:ethr:sepolia\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID Web resolution latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(credential_verifier_did_resolution_duration_seconds_bucket{cache_did=\"false\", did_provider=\"did:web\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DID:Ethr with cache end to end latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_message_end_to_end_latency_seconds_bucket{did_provider=\"did:ethr:sepolia\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kafka_consumer_credential_verification_duration_seconds_bucket{did_provider=\"did:ethr:sepolia\", cache_did=\"True\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}